// Comprehensive food database (per 100g unless noted)
export interface FoodDBItem {
  name: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  category?: string;
  fiber?: number;
}

export const FOOD_DATABASE: FoodDBItem[] = [
  // ═══════════════ МОЛОЧНЫЕ ПРОДУКТЫ ═══════════════
  { name: 'Творог 0%', calories: 71, protein: 18, carbs: 1.8, fat: 0.1, category: 'dairy' },
  { name: 'Творог 2%', calories: 103, protein: 18, carbs: 1.5, fat: 2, category: 'dairy' },
  { name: 'Творог 5%', calories: 121, protein: 17, carbs: 1.8, fat: 5, category: 'dairy' },
  { name: 'Творог 9%', calories: 159, protein: 16, carbs: 2, fat: 9, category: 'dairy' },
  { name: 'Творожная масса с изюмом', calories: 343, protein: 7, carbs: 30, fat: 23, category: 'dairy' },
  { name: 'Йогурт натуральный', calories: 60, protein: 4, carbs: 6, fat: 1.5, category: 'dairy' },
  { name: 'Йогурт греческий', calories: 97, protein: 9, carbs: 3.6, fat: 5, category: 'dairy' },
  { name: 'Йогурт питьевой', calories: 70, protein: 2.8, carbs: 11, fat: 1.5, category: 'dairy' },
  { name: 'Йогурт фруктовый', calories: 95, protein: 3.5, carbs: 15, fat: 2.5, category: 'dairy' },
  { name: 'Кефир 0%', calories: 30, protein: 3, carbs: 3.8, fat: 0.1, category: 'dairy' },
  { name: 'Кефир 1%', calories: 40, protein: 3, carbs: 4, fat: 1, category: 'dairy' },
  { name: 'Кефир 2.5%', calories: 50, protein: 2.9, carbs: 4, fat: 2.5, category: 'dairy' },
  { name: 'Ряженка 4%', calories: 67, protein: 2.8, carbs: 4.2, fat: 4, category: 'dairy' },
  { name: 'Молоко 1.5%', calories: 44, protein: 2.8, carbs: 4.7, fat: 1.5, category: 'dairy' },
  { name: 'Молоко 2.5%', calories: 52, protein: 2.8, carbs: 4.7, fat: 2.5, category: 'dairy' },
  { name: 'Молоко 3.2%', calories: 59, protein: 2.9, carbs: 4.7, fat: 3.2, category: 'dairy' },
  { name: 'Молоко топлёное', calories: 84, protein: 3, carbs: 4.7, fat: 6, category: 'dairy' },
  { name: 'Молоко растительное (овсяное)', calories: 45, protein: 1, carbs: 7, fat: 1.5, category: 'dairy' },
  { name: 'Молоко миндальное', calories: 17, protein: 0.6, carbs: 0.6, fat: 1.1, category: 'dairy' },
  { name: 'Молоко соевое', calories: 54, protein: 3.3, carbs: 6, fat: 1.8, category: 'dairy' },
  { name: 'Молоко кокосовое', calories: 230, protein: 2.3, carbs: 6, fat: 24, category: 'dairy' },
  { name: 'Сливки 10%', calories: 118, protein: 3, carbs: 4, fat: 10, category: 'dairy' },
  { name: 'Сливки 20%', calories: 205, protein: 2.8, carbs: 3.6, fat: 20, category: 'dairy' },
  { name: 'Сметана 15%', calories: 158, protein: 2.6, carbs: 3.6, fat: 15, category: 'dairy' },
  { name: 'Сметана 20%', calories: 206, protein: 2.8, carbs: 3.2, fat: 20, category: 'dairy' },
  { name: 'Масло сливочное', calories: 717, protein: 0.8, carbs: 0.1, fat: 81, category: 'dairy' },
  { name: 'Сыр твёрдый', calories: 350, protein: 26, carbs: 0, fat: 27, category: 'dairy' },
  { name: 'Сыр Российский', calories: 363, protein: 24, carbs: 0, fat: 29, category: 'dairy' },
  { name: 'Сыр Голландский', calories: 350, protein: 26, carbs: 0, fat: 27, category: 'dairy' },
  { name: 'Сыр Пармезан', calories: 392, protein: 36, carbs: 4, fat: 26, category: 'dairy' },
  { name: 'Сыр Чеддер', calories: 403, protein: 25, carbs: 1.3, fat: 33, category: 'dairy' },
  { name: 'Моцарелла', calories: 280, protein: 22, carbs: 2, fat: 20, category: 'dairy' },
  { name: 'Сыр Фета', calories: 264, protein: 14, carbs: 4, fat: 21, category: 'dairy' },
  { name: 'Сыр Адыгейский', calories: 240, protein: 18, carbs: 2, fat: 18, category: 'dairy' },
  { name: 'Сыр Бри', calories: 334, protein: 21, carbs: 0.5, fat: 28, category: 'dairy' },
  { name: 'Сыр плавленый', calories: 257, protein: 16, carbs: 3, fat: 20, category: 'dairy' },
  { name: 'Сыр Рикотта', calories: 174, protein: 11, carbs: 3, fat: 13, category: 'dairy' },
  { name: 'Сыр Сулугуни', calories: 290, protein: 20, carbs: 0.4, fat: 22, category: 'dairy' },
  { name: 'Мороженое пломбир', calories: 227, protein: 3.7, carbs: 23, fat: 13, category: 'dairy' },
  { name: 'Мороженое сливочное', calories: 183, protein: 3.5, carbs: 22, fat: 8, category: 'dairy' },

  // ═══════════════ МЯСО И ПТИЦА ═══════════════
  { name: 'Куриная грудка', calories: 165, protein: 31, carbs: 0, fat: 3.6, category: 'meat' },
  { name: 'Куриная грудка варёная', calories: 137, protein: 29, carbs: 0, fat: 1.8, category: 'meat' },
  { name: 'Куриная грудка гриль', calories: 148, protein: 30, carbs: 0, fat: 2.5, category: 'meat' },
  { name: 'Куриное бедро', calories: 210, protein: 26, carbs: 0, fat: 11, category: 'meat' },
  { name: 'Куриное бедро без кожи', calories: 177, protein: 24, carbs: 0, fat: 8, category: 'meat' },
  { name: 'Куриные крылышки', calories: 222, protein: 18, carbs: 0, fat: 16, category: 'meat' },
  { name: 'Куриная голень', calories: 172, protein: 20, carbs: 0, fat: 10, category: 'meat' },
  { name: 'Курица целая жареная', calories: 239, protein: 27, carbs: 0, fat: 14, category: 'meat' },
  { name: 'Куриная печень', calories: 136, protein: 19, carbs: 1, fat: 6, category: 'meat' },
  { name: 'Куриные наггетсы', calories: 297, protein: 15, carbs: 18, fat: 18, category: 'meat' },
  { name: 'Индейка филе', calories: 135, protein: 29, carbs: 0, fat: 1.5, category: 'meat' },
  { name: 'Индейка бедро', calories: 144, protein: 20, carbs: 0, fat: 7, category: 'meat' },
  { name: 'Говядина постная', calories: 187, protein: 26, carbs: 0, fat: 9, category: 'meat' },
  { name: 'Говядина', calories: 250, protein: 26, carbs: 0, fat: 16, category: 'meat' },
  { name: 'Говядина тушёная', calories: 232, protein: 25, carbs: 0, fat: 14, category: 'meat' },
  { name: 'Стейк рибай', calories: 291, protein: 24, carbs: 0, fat: 21, category: 'meat' },
  { name: 'Стейк филе-миньон', calories: 196, protein: 28, carbs: 0, fat: 9, category: 'meat' },
  { name: 'Стейк Нью-Йорк', calories: 234, protein: 27, carbs: 0, fat: 13, category: 'meat' },
  { name: 'Говяжья печень', calories: 135, protein: 20, carbs: 4, fat: 4, category: 'meat' },
  { name: 'Говяжий язык', calories: 173, protein: 16, carbs: 0, fat: 12, category: 'meat' },
  { name: 'Телятина', calories: 131, protein: 20, carbs: 0, fat: 5, category: 'meat' },
  { name: 'Свинина', calories: 242, protein: 19, carbs: 0, fat: 18, category: 'meat' },
  { name: 'Свинина постная', calories: 143, protein: 21, carbs: 0, fat: 6, category: 'meat' },
  { name: 'Свиная шея', calories: 343, protein: 14, carbs: 0, fat: 31, category: 'meat' },
  { name: 'Свиные рёбрышки', calories: 277, protein: 20, carbs: 0, fat: 22, category: 'meat' },
  { name: 'Свиная отбивная', calories: 231, protein: 25, carbs: 0, fat: 14, category: 'meat' },
  { name: 'Баранина', calories: 209, protein: 16, carbs: 0, fat: 16, category: 'meat' },
  { name: 'Кролик', calories: 156, protein: 21, carbs: 0, fat: 8, category: 'meat' },
  { name: 'Утка', calories: 337, protein: 19, carbs: 0, fat: 28, category: 'meat' },
  { name: 'Фарш куриный', calories: 143, protein: 17, carbs: 0, fat: 8, category: 'meat' },
  { name: 'Фарш говяжий', calories: 254, protein: 17, carbs: 0, fat: 20, category: 'meat' },
  { name: 'Фарш говяжий постный (5%)', calories: 137, protein: 21, carbs: 0, fat: 5, category: 'meat' },
  { name: 'Фарш свиной', calories: 263, protein: 17, carbs: 0, fat: 21, category: 'meat' },
  { name: 'Фарш индюшиный', calories: 150, protein: 20, carbs: 0, fat: 8, category: 'meat' },

  // ═══════════════ КОЛБАСНЫЕ ИЗДЕЛИЯ ═══════════════
  { name: 'Колбаса варёная Докторская', calories: 257, protein: 13, carbs: 2, fat: 22, category: 'meat' },
  { name: 'Колбаса копчёная', calories: 431, protein: 17, carbs: 2, fat: 40, category: 'meat' },
  { name: 'Сосиски молочные', calories: 266, protein: 11, carbs: 2, fat: 24, category: 'meat' },
  { name: 'Сардельки', calories: 215, protein: 11, carbs: 2, fat: 18, category: 'meat' },
  { name: 'Ветчина', calories: 145, protein: 17, carbs: 1, fat: 8, category: 'meat' },
  { name: 'Бекон', calories: 541, protein: 37, carbs: 1, fat: 42, category: 'meat' },
  { name: 'Пастрами', calories: 133, protein: 22, carbs: 1, fat: 5, category: 'meat' },
  { name: 'Салями', calories: 378, protein: 22, carbs: 2, fat: 31, category: 'meat' },
  { name: 'Буженина', calories: 180, protein: 15, carbs: 0, fat: 13, category: 'meat' },

  // ═══════════════ РЫБА И МОРЕПРОДУКТЫ ═══════════════
  { name: 'Лосось', calories: 208, protein: 20, carbs: 0, fat: 13, category: 'fish' },
  { name: 'Лосось на гриле', calories: 182, protein: 25, carbs: 0, fat: 8, category: 'fish' },
  { name: 'Лосось копчёный', calories: 117, protein: 18, carbs: 0, fat: 4.3, category: 'fish' },
  { name: 'Сёмга слабосолёная', calories: 195, protein: 22, carbs: 0, fat: 12, category: 'fish' },
  { name: 'Форель', calories: 148, protein: 21, carbs: 0, fat: 7, category: 'fish' },
  { name: 'Тунец', calories: 130, protein: 29, carbs: 0, fat: 1, category: 'fish' },
  { name: 'Тунец консервированный в масле', calories: 198, protein: 29, carbs: 0, fat: 8, category: 'fish' },
  { name: 'Тунец консервированный в собственном соку', calories: 116, protein: 26, carbs: 0, fat: 1, category: 'fish' },
  { name: 'Треска', calories: 82, protein: 18, carbs: 0, fat: 0.7, category: 'fish' },
  { name: 'Минтай', calories: 72, protein: 16, carbs: 0, fat: 0.9, category: 'fish' },
  { name: 'Тилапия', calories: 96, protein: 20, carbs: 0, fat: 1.7, category: 'fish' },
  { name: 'Скумбрия', calories: 191, protein: 18, carbs: 0, fat: 13, category: 'fish' },
  { name: 'Скумбрия копчёная', calories: 221, protein: 20, carbs: 0, fat: 15, category: 'fish' },
  { name: 'Сельдь', calories: 203, protein: 17, carbs: 0, fat: 15, category: 'fish' },
  { name: 'Сельдь солёная', calories: 217, protein: 19, carbs: 0, fat: 15, category: 'fish' },
  { name: 'Горбуша', calories: 127, protein: 21, carbs: 0, fat: 4, category: 'fish' },
  { name: 'Горбуша консервированная', calories: 136, protein: 20, carbs: 0, fat: 6, category: 'fish' },
  { name: 'Карп', calories: 112, protein: 18, carbs: 0, fat: 4, category: 'fish' },
  { name: 'Судак', calories: 84, protein: 18, carbs: 0, fat: 1.1, category: 'fish' },
  { name: 'Камбала', calories: 83, protein: 16, carbs: 0, fat: 1.8, category: 'fish' },
  { name: 'Дорадо', calories: 96, protein: 20, carbs: 0, fat: 1.8, category: 'fish' },
  { name: 'Окунь морской', calories: 103, protein: 18, carbs: 0, fat: 3, category: 'fish' },
  { name: 'Палтус', calories: 110, protein: 19, carbs: 0, fat: 3, category: 'fish' },
  { name: 'Креветки', calories: 99, protein: 24, carbs: 0, fat: 0.3, category: 'fish' },
  { name: 'Креветки тигровые', calories: 89, protein: 19, carbs: 0, fat: 1, category: 'fish' },
  { name: 'Кальмар', calories: 92, protein: 18, carbs: 1.4, fat: 1.4, category: 'fish' },
  { name: 'Мидии', calories: 86, protein: 12, carbs: 4, fat: 2, category: 'fish' },
  { name: 'Осьминог', calories: 82, protein: 15, carbs: 2, fat: 1, category: 'fish' },
  { name: 'Гребешки', calories: 88, protein: 17, carbs: 2, fat: 0.8, category: 'fish' },
  { name: 'Крабовые палочки', calories: 73, protein: 6, carbs: 10, fat: 1, category: 'fish' },
  { name: 'Икра красная (1 ст.л.)', calories: 40, protein: 4, carbs: 0.5, fat: 2.5, category: 'fish' },
  { name: 'Шпроты в масле', calories: 363, protein: 17, carbs: 0, fat: 32, category: 'fish' },
  { name: 'Сардины в масле', calories: 208, protein: 25, carbs: 0, fat: 11, category: 'fish' },

  // ═══════════════ ЯЙЦА ═══════════════
  { name: 'Яйцо куриное (1 шт)', calories: 75, protein: 6, carbs: 0.6, fat: 5, category: 'eggs' },
  { name: 'Яичный белок (1 шт)', calories: 17, protein: 3.6, carbs: 0.2, fat: 0.1, category: 'eggs' },
  { name: 'Яичный желток (1 шт)', calories: 55, protein: 2.7, carbs: 0.6, fat: 4.5, category: 'eggs' },
  { name: 'Яйцо перепелиное (1 шт)', calories: 14, protein: 1.2, carbs: 0, fat: 1, category: 'eggs' },
  { name: 'Яйцо варёное (1 шт)', calories: 78, protein: 6, carbs: 0.6, fat: 5.3, category: 'eggs' },
  { name: 'Омлет (2 яйца)', calories: 180, protein: 13, carbs: 1, fat: 14, category: 'eggs' },
  { name: 'Яичница-глазунья (2 яйца)', calories: 196, protein: 13, carbs: 1, fat: 15, category: 'eggs' },

  // ═══════════════ КРУПЫ И ЗЛАКИ ═══════════════
  { name: 'Рис белый варёный', calories: 130, protein: 2.7, carbs: 28, fat: 0.3, category: 'grains' },
  { name: 'Рис бурый варёный', calories: 111, protein: 2.6, carbs: 23, fat: 0.9, category: 'grains' },
  { name: 'Рис басмати варёный', calories: 121, protein: 3.5, carbs: 25, fat: 0.4, category: 'grains' },
  { name: 'Рис дикий варёный', calories: 101, protein: 4, carbs: 21, fat: 0.3, category: 'grains' },
  { name: 'Гречка варёная', calories: 110, protein: 4.5, carbs: 21, fat: 1.1, category: 'grains' },
  { name: 'Гречка сухая', calories: 313, protein: 13, carbs: 62, fat: 3.3, category: 'grains' },
  { name: 'Овсянка на воде', calories: 88, protein: 3, carbs: 15, fat: 1.7, category: 'grains' },
  { name: 'Овсянка на молоке', calories: 102, protein: 4, carbs: 14, fat: 3.2, category: 'grains' },
  { name: 'Овсяные хлопья сухие', calories: 379, protein: 13, carbs: 66, fat: 7, category: 'grains' },
  { name: 'Геркулес сухой', calories: 352, protein: 12, carbs: 61, fat: 6, category: 'grains' },
  { name: 'Мюсли', calories: 340, protein: 8, carbs: 56, fat: 10, category: 'grains' },
  { name: 'Гранола', calories: 471, protein: 10, carbs: 64, fat: 20, category: 'grains' },
  { name: 'Макароны варёные', calories: 131, protein: 5, carbs: 27, fat: 0.5, category: 'grains' },
  { name: 'Макароны из цельнозерновой муки', calories: 124, protein: 5, carbs: 25, fat: 0.5, category: 'grains' },
  { name: 'Спагетти варёные', calories: 131, protein: 5, carbs: 25, fat: 1, category: 'grains' },
  { name: 'Лапша рисовая варёная', calories: 109, protein: 0.9, carbs: 25, fat: 0.2, category: 'grains' },
  { name: 'Лапша яичная варёная', calories: 138, protein: 5, carbs: 25, fat: 2, category: 'grains' },
  { name: 'Булгур варёный', calories: 83, protein: 3, carbs: 14, fat: 0.2, category: 'grains' },
  { name: 'Кускус варёный', calories: 112, protein: 3.8, carbs: 23, fat: 0.2, category: 'grains' },
  { name: 'Киноа варёная', calories: 120, protein: 4, carbs: 21, fat: 2, category: 'grains' },
  { name: 'Перловка варёная', calories: 109, protein: 2.3, carbs: 22, fat: 0.4, category: 'grains' },
  { name: 'Пшено варёное', calories: 90, protein: 3, carbs: 17, fat: 1, category: 'grains' },
  { name: 'Кукурузная каша', calories: 86, protein: 2, carbs: 17, fat: 1, category: 'grains' },
  { name: 'Манная каша на молоке', calories: 98, protein: 3, carbs: 16, fat: 3, category: 'grains' },
  { name: 'Нут варёный', calories: 164, protein: 9, carbs: 27, fat: 2.6, category: 'grains', fiber: 8 },
  { name: 'Чечевица варёная', calories: 116, protein: 9, carbs: 20, fat: 0.4, category: 'grains', fiber: 8 },
  { name: 'Фасоль красная варёная', calories: 127, protein: 9, carbs: 22, fat: 0.5, category: 'grains', fiber: 8 },
  { name: 'Фасоль белая варёная', calories: 139, protein: 9, carbs: 25, fat: 0.4, category: 'grains', fiber: 7 },
  { name: 'Горох варёный', calories: 81, protein: 5, carbs: 14, fat: 0.4, category: 'grains', fiber: 5 },
  { name: 'Маш варёный', calories: 105, protein: 7, carbs: 19, fat: 0.4, category: 'grains', fiber: 8 },
  { name: 'Соя варёная', calories: 141, protein: 12, carbs: 11, fat: 6, category: 'grains' },
  { name: 'Тофу', calories: 76, protein: 8, carbs: 2, fat: 4.8, category: 'grains' },

  // ═══════════════ КАРТОФЕЛЬ ═══════════════
  { name: 'Картофель варёный', calories: 82, protein: 2, carbs: 17, fat: 0.1, category: 'grains' },
  { name: 'Картофель запечённый', calories: 93, protein: 2, carbs: 21, fat: 0.1, category: 'grains' },
  { name: 'Пюре картофельное', calories: 106, protein: 2, carbs: 16, fat: 4, category: 'grains' },
  { name: 'Картофель фри', calories: 312, protein: 3.4, carbs: 41, fat: 15, category: 'grains' },
  { name: 'Батат (сладкий картофель)', calories: 86, protein: 1.6, carbs: 20, fat: 0.1, category: 'grains' },

  // ═══════════════ ХЛЕБ И ВЫПЕЧКА ═══════════════
  { name: 'Хлеб ржаной (1 кусок)', calories: 65, protein: 2, carbs: 12, fat: 0.7, category: 'bread' },
  { name: 'Хлеб белый (1 кусок)', calories: 75, protein: 2.5, carbs: 14, fat: 0.8, category: 'bread' },
  { name: 'Хлеб цельнозерновой (1 кусок)', calories: 69, protein: 3.5, carbs: 12, fat: 1, category: 'bread' },
  { name: 'Хлеб бородинский (1 кусок)', calories: 58, protein: 2, carbs: 10, fat: 0.5, category: 'bread' },
  { name: 'Хлеб Дарницкий (1 кусок)', calories: 62, protein: 2, carbs: 11, fat: 0.7, category: 'bread' },
  { name: 'Хлебцы ржаные (1 шт)', calories: 30, protein: 1, carbs: 6, fat: 0.2, category: 'bread' },
  { name: 'Хлебцы рисовые (1 шт)', calories: 35, protein: 0.7, carbs: 8, fat: 0.2, category: 'bread' },
  { name: 'Тост пшеничный (1 шт)', calories: 85, protein: 2.5, carbs: 15, fat: 1.5, category: 'bread' },
  { name: 'Лаваш тонкий', calories: 236, protein: 8, carbs: 48, fat: 0.7, category: 'bread' },
  { name: 'Пита (1 шт)', calories: 165, protein: 5, carbs: 33, fat: 1, category: 'bread' },
  { name: 'Тортилья пшеничная (1 шт)', calories: 146, protein: 4, carbs: 24, fat: 3.5, category: 'bread' },
  { name: 'Багет (1 кусок)', calories: 88, protein: 3, carbs: 17, fat: 1, category: 'bread' },
  { name: 'Круассан (1 шт)', calories: 231, protein: 4, carbs: 26, fat: 12, category: 'bread' },
  { name: 'Булочка с маком', calories: 292, protein: 7, carbs: 50, fat: 8, category: 'bread' },
  { name: 'Блин (1 шт)', calories: 84, protein: 2.5, carbs: 12, fat: 3, category: 'bread' },
  { name: 'Оладьи (1 шт)', calories: 85, protein: 2, carbs: 10, fat: 4, category: 'bread' },
  { name: 'Сухари', calories: 331, protein: 11, carbs: 72, fat: 1.4, category: 'bread' },

  // ═══════════════ ОВОЩИ ═══════════════
  { name: 'Огурец', calories: 15, protein: 0.7, carbs: 2.8, fat: 0.1, category: 'vegetables' },
  { name: 'Помидор', calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2, category: 'vegetables' },
  { name: 'Помидоры черри', calories: 18, protein: 0.9, carbs: 4, fat: 0.1, category: 'vegetables' },
  { name: 'Авокадо', calories: 160, protein: 2, carbs: 9, fat: 15, category: 'vegetables' },
  { name: 'Брокколи', calories: 34, protein: 2.8, carbs: 7, fat: 0.4, category: 'vegetables' },
  { name: 'Брокколи на пару', calories: 35, protein: 2.4, carbs: 7, fat: 0.4, category: 'vegetables' },
  { name: 'Цветная капуста', calories: 25, protein: 2, carbs: 5, fat: 0.3, category: 'vegetables' },
  { name: 'Капуста белокочанная', calories: 25, protein: 1.3, carbs: 6, fat: 0.1, category: 'vegetables' },
  { name: 'Капуста пекинская', calories: 13, protein: 1.2, carbs: 2, fat: 0.2, category: 'vegetables' },
  { name: 'Капуста брюссельская', calories: 43, protein: 3.4, carbs: 9, fat: 0.3, category: 'vegetables' },
  { name: 'Капуста квашеная', calories: 19, protein: 1, carbs: 4, fat: 0.1, category: 'vegetables' },
  { name: 'Морковь', calories: 41, protein: 0.9, carbs: 10, fat: 0.2, category: 'vegetables' },
  { name: 'Морковь варёная', calories: 35, protein: 0.8, carbs: 8, fat: 0.2, category: 'vegetables' },
  { name: 'Свёкла', calories: 43, protein: 1.6, carbs: 10, fat: 0.2, category: 'vegetables' },
  { name: 'Свёкла варёная', calories: 44, protein: 1.7, carbs: 10, fat: 0.2, category: 'vegetables' },
  { name: 'Перец болгарский', calories: 27, protein: 1, carbs: 5, fat: 0.3, category: 'vegetables' },
  { name: 'Перец чили', calories: 40, protein: 2, carbs: 9, fat: 0.4, category: 'vegetables' },
  { name: 'Баклажан', calories: 25, protein: 1, carbs: 6, fat: 0.2, category: 'vegetables' },
  { name: 'Кабачок', calories: 17, protein: 1.2, carbs: 3, fat: 0.3, category: 'vegetables' },
  { name: 'Тыква', calories: 26, protein: 1, carbs: 7, fat: 0.1, category: 'vegetables' },
  { name: 'Шпинат', calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, category: 'vegetables' },
  { name: 'Руккола', calories: 25, protein: 2.6, carbs: 3.7, fat: 0.7, category: 'vegetables' },
  { name: 'Салат айсберг', calories: 14, protein: 0.9, carbs: 3, fat: 0.1, category: 'vegetables' },
  { name: 'Салат Романо', calories: 17, protein: 1.2, carbs: 3.3, fat: 0.3, category: 'vegetables' },
  { name: 'Салат листовой', calories: 15, protein: 1.4, carbs: 2, fat: 0.2, category: 'vegetables' },
  { name: 'Лук репчатый', calories: 40, protein: 1, carbs: 9, fat: 0.1, category: 'vegetables' },
  { name: 'Лук зелёный', calories: 32, protein: 1.8, carbs: 7, fat: 0.2, category: 'vegetables' },
  { name: 'Чеснок', calories: 149, protein: 6, carbs: 33, fat: 0.5, category: 'vegetables' },
  { name: 'Имбирь', calories: 80, protein: 1.8, carbs: 18, fat: 0.8, category: 'vegetables' },
  { name: 'Редис', calories: 16, protein: 0.7, carbs: 3.4, fat: 0.1, category: 'vegetables' },
  { name: 'Сельдерей', calories: 16, protein: 0.7, carbs: 3, fat: 0.2, category: 'vegetables' },
  { name: 'Стручковая фасоль', calories: 31, protein: 1.8, carbs: 7, fat: 0.1, category: 'vegetables' },
  { name: 'Зелёный горошек', calories: 81, protein: 5, carbs: 14, fat: 0.4, category: 'vegetables' },
  { name: 'Кукуруза варёная', calories: 96, protein: 3.4, carbs: 21, fat: 1.5, category: 'vegetables' },
  { name: 'Кукуруза консервированная', calories: 64, protein: 2, carbs: 12, fat: 0.5, category: 'vegetables' },
  { name: 'Грибы шампиньоны', calories: 27, protein: 4, carbs: 1, fat: 0.3, category: 'vegetables' },
  { name: 'Грибы шампиньоны жареные', calories: 43, protein: 3, carbs: 2, fat: 3, category: 'vegetables' },
  { name: 'Грибы вёшенки', calories: 33, protein: 3, carbs: 6, fat: 0.4, category: 'vegetables' },
  { name: 'Оливки', calories: 115, protein: 0.8, carbs: 6, fat: 11, category: 'vegetables' },
  { name: 'Маслины', calories: 166, protein: 1, carbs: 4, fat: 15, category: 'vegetables' },
  { name: 'Водоросли нори (1 лист)', calories: 9, protein: 1, carbs: 1, fat: 0.1, category: 'vegetables' },
  { name: 'Спаржа', calories: 20, protein: 2.2, carbs: 4, fat: 0.1, category: 'vegetables' },
  { name: 'Артишок', calories: 47, protein: 3, carbs: 11, fat: 0.2, category: 'vegetables' },

  // ═══════════════ ФРУКТЫ И ЯГОДЫ ═══════════════
  { name: 'Яблоко', calories: 52, protein: 0.3, carbs: 14, fat: 0.2, category: 'fruits' },
  { name: 'Банан', calories: 89, protein: 1.1, carbs: 23, fat: 0.3, category: 'fruits' },
  { name: 'Апельсин', calories: 43, protein: 0.9, carbs: 10, fat: 0.1, category: 'fruits' },
  { name: 'Мандарин', calories: 38, protein: 0.8, carbs: 8, fat: 0.3, category: 'fruits' },
  { name: 'Грейпфрут', calories: 42, protein: 0.8, carbs: 11, fat: 0.1, category: 'fruits' },
  { name: 'Лимон', calories: 29, protein: 1.1, carbs: 9, fat: 0.3, category: 'fruits' },
  { name: 'Лайм', calories: 30, protein: 0.7, carbs: 11, fat: 0.2, category: 'fruits' },
  { name: 'Груша', calories: 57, protein: 0.4, carbs: 15, fat: 0.1, category: 'fruits' },
  { name: 'Персик', calories: 39, protein: 0.9, carbs: 10, fat: 0.3, category: 'fruits' },
  { name: 'Нектарин', calories: 44, protein: 1.1, carbs: 11, fat: 0.3, category: 'fruits' },
  { name: 'Абрикос', calories: 48, protein: 1.4, carbs: 11, fat: 0.4, category: 'fruits' },
  { name: 'Слива', calories: 46, protein: 0.7, carbs: 11, fat: 0.3, category: 'fruits' },
  { name: 'Вишня', calories: 50, protein: 1, carbs: 12, fat: 0.3, category: 'fruits' },
  { name: 'Черешня', calories: 50, protein: 1, carbs: 12, fat: 0.2, category: 'fruits' },
  { name: 'Клубника', calories: 33, protein: 0.7, carbs: 8, fat: 0.3, category: 'fruits' },
  { name: 'Малина', calories: 46, protein: 0.8, carbs: 12, fat: 0.7, category: 'fruits' },
  { name: 'Черника', calories: 57, protein: 0.7, carbs: 14, fat: 0.3, category: 'fruits' },
  { name: 'Голубика', calories: 35, protein: 0.5, carbs: 8, fat: 0.3, category: 'fruits' },
  { name: 'Ежевика', calories: 43, protein: 1.4, carbs: 10, fat: 0.5, category: 'fruits' },
  { name: 'Смородина чёрная', calories: 44, protein: 1, carbs: 10, fat: 0.4, category: 'fruits' },
  { name: 'Смородина красная', calories: 43, protein: 0.6, carbs: 11, fat: 0.2, category: 'fruits' },
  { name: 'Крыжовник', calories: 44, protein: 0.9, carbs: 10, fat: 0.6, category: 'fruits' },
  { name: 'Виноград', calories: 69, protein: 0.7, carbs: 18, fat: 0.2, category: 'fruits' },
  { name: 'Арбуз', calories: 30, protein: 0.6, carbs: 8, fat: 0.2, category: 'fruits' },
  { name: 'Дыня', calories: 34, protein: 0.8, carbs: 8, fat: 0.2, category: 'fruits' },
  { name: 'Ананас', calories: 50, protein: 0.5, carbs: 13, fat: 0.1, category: 'fruits' },
  { name: 'Манго', calories: 60, protein: 0.8, carbs: 15, fat: 0.4, category: 'fruits' },
  { name: 'Киви', calories: 61, protein: 1.1, carbs: 15, fat: 0.5, category: 'fruits' },
  { name: 'Гранат', calories: 72, protein: 0.9, carbs: 14, fat: 0.6, category: 'fruits' },
  { name: 'Хурма', calories: 67, protein: 0.5, carbs: 16, fat: 0.3, category: 'fruits' },
  { name: 'Помело', calories: 38, protein: 0.8, carbs: 10, fat: 0, category: 'fruits' },
  { name: 'Папайя', calories: 43, protein: 0.5, carbs: 11, fat: 0.3, category: 'fruits' },
  { name: 'Маракуйя', calories: 97, protein: 2.2, carbs: 23, fat: 0.7, category: 'fruits' },
  { name: 'Личи', calories: 66, protein: 0.8, carbs: 17, fat: 0.4, category: 'fruits' },
  { name: 'Инжир', calories: 74, protein: 0.8, carbs: 19, fat: 0.3, category: 'fruits' },
  { name: 'Финики (1 шт)', calories: 23, protein: 0.2, carbs: 6, fat: 0, category: 'fruits' },

  // ═══════════════ СУХОФРУКТЫ ═══════════════
  { name: 'Изюм', calories: 299, protein: 3, carbs: 79, fat: 0.5, category: 'fruits' },
  { name: 'Курага', calories: 241, protein: 3.4, carbs: 63, fat: 0.5, category: 'fruits' },
  { name: 'Чернослив', calories: 240, protein: 2.2, carbs: 64, fat: 0.4, category: 'fruits' },
  { name: 'Финики сушёные', calories: 277, protein: 2.5, carbs: 75, fat: 0.2, category: 'fruits' },
  { name: 'Инжир сушёный', calories: 249, protein: 3, carbs: 64, fat: 0.9, category: 'fruits' },
  { name: 'Клюква сушёная', calories: 308, protein: 0.1, carbs: 82, fat: 1.4, category: 'fruits' },

  // ═══════════════ ОРЕХИ И СЕМЕНА ═══════════════
  { name: 'Миндаль (30г)', calories: 173, protein: 6, carbs: 6, fat: 15, category: 'nuts' },
  { name: 'Грецкий орех (30г)', calories: 196, protein: 5, carbs: 4, fat: 20, category: 'nuts' },
  { name: 'Арахис (30г)', calories: 170, protein: 8, carbs: 5, fat: 14, category: 'nuts' },
  { name: 'Кешью (30г)', calories: 157, protein: 5, carbs: 9, fat: 12, category: 'nuts' },
  { name: 'Фундук (30г)', calories: 188, protein: 4, carbs: 5, fat: 18, category: 'nuts' },
  { name: 'Фисташки (30г)', calories: 168, protein: 6, carbs: 8, fat: 14, category: 'nuts' },
  { name: 'Кедровые орехи (30г)', calories: 202, protein: 4, carbs: 4, fat: 20, category: 'nuts' },
  { name: 'Макадамия (30г)', calories: 214, protein: 2, carbs: 4, fat: 23, category: 'nuts' },
  { name: 'Пекан (30г)', calories: 207, protein: 3, carbs: 4, fat: 22, category: 'nuts' },
  { name: 'Бразильский орех (30г)', calories: 196, protein: 4, carbs: 4, fat: 19, category: 'nuts' },
  { name: 'Семена подсолнечника (30г)', calories: 175, protein: 6, carbs: 6, fat: 15, category: 'nuts' },
  { name: 'Семена тыквы (30г)', calories: 170, protein: 7, carbs: 5, fat: 15, category: 'nuts' },
  { name: 'Семена чиа (1 ст.л.)', calories: 58, protein: 2, carbs: 5, fat: 4, category: 'nuts' },
  { name: 'Семена льна (1 ст.л.)', calories: 55, protein: 2, carbs: 3, fat: 4, category: 'nuts' },
  { name: 'Семена кунжута (1 ст.л.)', calories: 52, protein: 2, carbs: 2, fat: 4, category: 'nuts' },
  { name: 'Кокосовая стружка', calories: 660, protein: 7, carbs: 24, fat: 65, category: 'nuts' },
  { name: 'Арахисовая паста (1 ст.л.)', calories: 94, protein: 4, carbs: 3, fat: 8, category: 'nuts' },
  { name: 'Миндальная паста (1 ст.л.)', calories: 98, protein: 3, carbs: 3, fat: 9, category: 'nuts' },

  // ═══════════════ МАСЛА И СОУСЫ ═══════════════
  { name: 'Масло оливковое (1 ст.л.)', calories: 119, protein: 0, carbs: 0, fat: 14, category: 'oils' },
  { name: 'Масло подсолнечное (1 ст.л.)', calories: 120, protein: 0, carbs: 0, fat: 14, category: 'oils' },
  { name: 'Масло кокосовое (1 ст.л.)', calories: 117, protein: 0, carbs: 0, fat: 14, category: 'oils' },
  { name: 'Масло льняное (1 ст.л.)', calories: 120, protein: 0, carbs: 0, fat: 14, category: 'oils' },
  { name: 'Масло кунжутное (1 ст.л.)', calories: 120, protein: 0, carbs: 0, fat: 14, category: 'oils' },
  { name: 'Майонез (1 ст.л.)', calories: 94, protein: 0.1, carbs: 0.6, fat: 10, category: 'oils' },
  { name: 'Майонез лёгкий (1 ст.л.)', calories: 49, protein: 0.1, carbs: 2, fat: 5, category: 'oils' },
  { name: 'Кетчуп (1 ст.л.)', calories: 17, protein: 0.2, carbs: 4, fat: 0, category: 'oils' },
  { name: 'Горчица (1 ст.л.)', calories: 10, protein: 0.7, carbs: 0.5, fat: 0.6, category: 'oils' },
  { name: 'Соевый соус (1 ст.л.)', calories: 8, protein: 1, carbs: 1, fat: 0, category: 'oils' },
  { name: 'Хумус', calories: 166, protein: 8, carbs: 14, fat: 10, category: 'oils' },
  { name: 'Гуакамоле', calories: 160, protein: 2, carbs: 9, fat: 15, category: 'oils' },
  { name: 'Песто (1 ст.л.)', calories: 80, protein: 2, carbs: 1, fat: 8, category: 'oils' },
  { name: 'Томатная паста (1 ст.л.)', calories: 13, protein: 0.7, carbs: 3, fat: 0.1, category: 'oils' },
  { name: 'Сальса', calories: 36, protein: 2, carbs: 8, fat: 0.2, category: 'oils' },
  { name: 'Соус терияки (1 ст.л.)', calories: 16, protein: 1, carbs: 3, fat: 0, category: 'oils' },
  { name: 'Соус барбекю (1 ст.л.)', calories: 29, protein: 0.2, carbs: 7, fat: 0, category: 'oils' },
  { name: 'Табаско (1 ч.л.)', calories: 1, protein: 0, carbs: 0, fat: 0, category: 'oils' },

  // ═══════════════ ГОТОВЫЕ БЛЮДА ═══════════════
  { name: 'Овсянка с бананом', calories: 220, protein: 6, carbs: 40, fat: 4, category: 'meals' },
  { name: 'Овсянка с ягодами', calories: 180, protein: 5, carbs: 32, fat: 3, category: 'meals' },
  { name: 'Каша рисовая молочная', calories: 97, protein: 2.5, carbs: 16, fat: 3, category: 'meals' },
  { name: 'Каша гречневая с молоком', calories: 118, protein: 4, carbs: 18, fat: 3, category: 'meals' },
  { name: 'Салат Цезарь', calories: 180, protein: 12, carbs: 8, fat: 12, category: 'meals' },
  { name: 'Салат Греческий', calories: 90, protein: 3, carbs: 5, fat: 7, category: 'meals' },
  { name: 'Салат овощной', calories: 30, protein: 1, carbs: 5, fat: 0.5, category: 'meals' },
  { name: 'Салат с тунцом', calories: 144, protein: 13, carbs: 5, fat: 8, category: 'meals' },
  { name: 'Оливье', calories: 198, protein: 6, carbs: 10, fat: 15, category: 'meals' },
  { name: 'Винегрет', calories: 130, protein: 1.7, carbs: 10, fat: 10, category: 'meals' },
  { name: 'Суп куриный', calories: 86, protein: 7, carbs: 5, fat: 4, category: 'meals' },
  { name: 'Суп-пюре тыквенный', calories: 48, protein: 1.5, carbs: 6, fat: 2, category: 'meals' },
  { name: 'Суп-пюре грибной', calories: 65, protein: 2, carbs: 5, fat: 4, category: 'meals' },
  { name: 'Суп гороховый', calories: 66, protein: 4, carbs: 9, fat: 2, category: 'meals' },
  { name: 'Суп рассольник', calories: 42, protein: 2, carbs: 5, fat: 2, category: 'meals' },
  { name: 'Суп харчо', calories: 75, protein: 5, carbs: 5, fat: 4, category: 'meals' },
  { name: 'Солянка', calories: 69, protein: 5, carbs: 3, fat: 4, category: 'meals' },
  { name: 'Уха', calories: 46, protein: 5, carbs: 3, fat: 1.5, category: 'meals' },
  { name: 'Борщ', calories: 49, protein: 2, carbs: 5, fat: 2, category: 'meals' },
  { name: 'Щи', calories: 31, protein: 2, carbs: 4, fat: 1, category: 'meals' },
  { name: 'Окрошка на кефире', calories: 47, protein: 3, carbs: 4, fat: 2, category: 'meals' },
  { name: 'Плов', calories: 150, protein: 7, carbs: 18, fat: 6, category: 'meals' },
  { name: 'Плов с курицей', calories: 165, protein: 12, carbs: 18, fat: 5, category: 'meals' },
  { name: 'Котлета куриная', calories: 190, protein: 18, carbs: 8, fat: 10, category: 'meals' },
  { name: 'Котлета говяжья', calories: 220, protein: 15, carbs: 8, fat: 14, category: 'meals' },
  { name: 'Котлета рыбная', calories: 168, protein: 12, carbs: 6, fat: 11, category: 'meals' },
  { name: 'Тефтели', calories: 198, protein: 13, carbs: 10, fat: 12, category: 'meals' },
  { name: 'Голубцы', calories: 95, protein: 5, carbs: 8, fat: 5, category: 'meals' },
  { name: 'Фрикадельки', calories: 204, protein: 13, carbs: 6, fat: 14, category: 'meals' },
  { name: 'Сырники (2 шт)', calories: 220, protein: 14, carbs: 18, fat: 10, category: 'meals' },
  { name: 'Запеканка творожная', calories: 168, protein: 12, carbs: 17, fat: 6, category: 'meals' },
  { name: 'Пельмени (10 шт)', calories: 275, protein: 12, carbs: 29, fat: 12, category: 'meals' },
  { name: 'Вареники с картошкой (5 шт)', calories: 220, protein: 5, carbs: 33, fat: 8, category: 'meals' },
  { name: 'Вареники с творогом (5 шт)', calories: 230, protein: 10, carbs: 30, fat: 8, category: 'meals' },
  { name: 'Манты (3 шт)', calories: 300, protein: 12, carbs: 28, fat: 16, category: 'meals' },
  { name: 'Чебурек (1 шт)', calories: 264, protein: 9, carbs: 21, fat: 16, category: 'meals' },
  { name: 'Беляш (1 шт)', calories: 232, protein: 8, carbs: 18, fat: 14, category: 'meals' },
  { name: 'Блины с мясом (2 шт)', calories: 250, protein: 12, carbs: 22, fat: 13, category: 'meals' },
  { name: 'Шаурма (1 шт)', calories: 260, protein: 12, carbs: 20, fat: 15, category: 'meals' },
  { name: 'Шашлык свиной', calories: 324, protein: 20, carbs: 0, fat: 27, category: 'meals' },
  { name: 'Шашлык куриный', calories: 180, protein: 25, carbs: 1, fat: 8, category: 'meals' },

  // ═══════════════ МЕЖДУНАРОДНАЯ КУХНЯ ═══════════════
  { name: 'Суши Филадельфия (6 шт)', calories: 250, protein: 9, carbs: 28, fat: 11, category: 'meals' },
  { name: 'Суши с лососем (6 шт)', calories: 210, protein: 9, carbs: 28, fat: 7, category: 'meals' },
  { name: 'Ролл Калифорния (6 шт)', calories: 225, protein: 7, carbs: 28, fat: 9, category: 'meals' },
  { name: 'Рамен', calories: 190, protein: 10, carbs: 22, fat: 7, category: 'meals' },
  { name: 'Том Ям', calories: 30, protein: 2, carbs: 3, fat: 1, category: 'meals' },
  { name: 'Пад Тай', calories: 140, protein: 7, carbs: 19, fat: 4, category: 'meals' },
  { name: 'Карри с курицей', calories: 150, protein: 15, carbs: 6, fat: 8, category: 'meals' },
  { name: 'Лазанья', calories: 135, protein: 8, carbs: 13, fat: 6, category: 'meals' },
  { name: 'Паста Карбонара', calories: 190, protein: 9, carbs: 22, fat: 8, category: 'meals' },
  { name: 'Паста Болоньезе', calories: 160, protein: 10, carbs: 18, fat: 5, category: 'meals' },
  { name: 'Пицца Маргарита (1 кусок)', calories: 206, protein: 8, carbs: 26, fat: 8, category: 'meals' },
  { name: 'Пицца Пепперони (1 кусок)', calories: 248, protein: 10, carbs: 25, fat: 12, category: 'meals' },
  { name: 'Бургер классический', calories: 295, protein: 17, carbs: 24, fat: 14, category: 'meals' },
  { name: 'Чизбургер', calories: 303, protein: 15, carbs: 25, fat: 15, category: 'meals' },
  { name: 'Хот-дог', calories: 290, protein: 10, carbs: 24, fat: 17, category: 'meals' },
  { name: 'Тако (1 шт)', calories: 156, protein: 8, carbs: 13, fat: 8, category: 'meals' },
  { name: 'Буррито', calories: 206, protein: 9, carbs: 22, fat: 9, category: 'meals' },
  { name: 'Фалафель (3 шт)', calories: 213, protein: 7, carbs: 18, fat: 13, category: 'meals' },
  { name: 'Кебаб', calories: 226, protein: 17, carbs: 2, fat: 17, category: 'meals' },
  { name: 'Донер', calories: 215, protein: 16, carbs: 14, fat: 11, category: 'meals' },

  // ═══════════════ ФАСТФУД ═══════════════
  { name: 'Картофель фри (средняя порция)', calories: 365, protein: 4, carbs: 48, fat: 17, category: 'fastfood' },
  { name: 'Наггетсы (6 шт)', calories: 280, protein: 14, carbs: 18, fat: 17, category: 'fastfood' },
  { name: 'Чикен стрипс (3 шт)', calories: 270, protein: 18, carbs: 15, fat: 15, category: 'fastfood' },
  { name: 'Луковые кольца (порция)', calories: 410, protein: 5, carbs: 45, fat: 23, category: 'fastfood' },
  { name: 'Сэндвич с курицей', calories: 350, protein: 22, carbs: 34, fat: 14, category: 'fastfood' },
  { name: 'Сэндвич с ветчиной', calories: 290, protein: 16, carbs: 30, fat: 12, category: 'fastfood' },
  { name: 'Сэндвич с тунцом', calories: 310, protein: 20, carbs: 28, fat: 13, category: 'fastfood' },

  // ═══════════════ НАПИТКИ ═══════════════
  { name: 'Вода', calories: 0, protein: 0, carbs: 0, fat: 0, category: 'drinks' },
  { name: 'Чай чёрный без сахара', calories: 1, protein: 0, carbs: 0, fat: 0, category: 'drinks' },
  { name: 'Чай зелёный без сахара', calories: 1, protein: 0, carbs: 0, fat: 0, category: 'drinks' },
  { name: 'Кофе чёрный', calories: 2, protein: 0.3, carbs: 0, fat: 0, category: 'drinks' },
  { name: 'Кофе с молоком', calories: 25, protein: 1, carbs: 2, fat: 1, category: 'drinks' },
  { name: 'Кофе латте', calories: 120, protein: 6, carbs: 10, fat: 6, category: 'drinks' },
  { name: 'Кофе капучино', calories: 80, protein: 4, carbs: 6, fat: 4, category: 'drinks' },
  { name: 'Кофе Американо', calories: 9, protein: 0.3, carbs: 2, fat: 0, category: 'drinks' },
  { name: 'Эспрессо (1 порция)', calories: 3, protein: 0.2, carbs: 0.5, fat: 0, category: 'drinks' },
  { name: 'Моккачино', calories: 170, protein: 5, carbs: 24, fat: 6, category: 'drinks' },
  { name: 'Раф-кофе', calories: 190, protein: 4, carbs: 20, fat: 10, category: 'drinks' },
  { name: 'Фраппучино', calories: 200, protein: 3, carbs: 34, fat: 6, category: 'drinks' },
  { name: 'Какао на молоке', calories: 80, protein: 3, carbs: 10, fat: 3, category: 'drinks' },
  { name: 'Горячий шоколад', calories: 105, protein: 3, carbs: 14, fat: 4, category: 'drinks' },
  { name: 'Протеиновый коктейль', calories: 120, protein: 24, carbs: 3, fat: 1.5, category: 'drinks' },
  { name: 'Смузи ягодный', calories: 110, protein: 2, carbs: 24, fat: 0.5, category: 'drinks' },
  { name: 'Смузи банановый', calories: 135, protein: 3, carbs: 30, fat: 1, category: 'drinks' },
  { name: 'Смузи зелёный', calories: 80, protein: 2, carbs: 16, fat: 1, category: 'drinks' },
  { name: 'Сок апельсиновый (200 мл)', calories: 88, protein: 1.4, carbs: 20, fat: 0.4, category: 'drinks' },
  { name: 'Сок яблочный (200 мл)', calories: 92, protein: 0.2, carbs: 22, fat: 0.2, category: 'drinks' },
  { name: 'Сок томатный (200 мл)', calories: 34, protein: 1.6, carbs: 7, fat: 0.2, category: 'drinks' },
  { name: 'Сок морковный (200 мл)', calories: 80, protein: 2, carbs: 18, fat: 0.2, category: 'drinks' },
  { name: 'Сок гранатовый (200 мл)', calories: 108, protein: 0.6, carbs: 26, fat: 0.6, category: 'drinks' },
  { name: 'Морс клюквенный (200 мл)', calories: 42, protein: 0, carbs: 11, fat: 0, category: 'drinks' },
  { name: 'Компот (200 мл)', calories: 60, protein: 0.2, carbs: 15, fat: 0, category: 'drinks' },
  { name: 'Кисель (200 мл)', calories: 68, protein: 0.2, carbs: 16, fat: 0, category: 'drinks' },
  { name: 'Квас (200 мл)', calories: 54, protein: 0.4, carbs: 13, fat: 0, category: 'drinks' },
  { name: 'Кола (330 мл)', calories: 139, protein: 0, carbs: 35, fat: 0, category: 'drinks' },
  { name: 'Кола Зеро (330 мл)', calories: 1, protein: 0, carbs: 0, fat: 0, category: 'drinks' },
  { name: 'Спрайт (330 мл)', calories: 128, protein: 0, carbs: 32, fat: 0, category: 'drinks' },
  { name: 'Энергетик (250 мл)', calories: 110, protein: 0, carbs: 28, fat: 0, category: 'drinks' },
  { name: 'Лимонад (200 мл)', calories: 84, protein: 0, carbs: 21, fat: 0, category: 'drinks' },
  { name: 'Айран (200 мл)', calories: 56, protein: 2, carbs: 4, fat: 3, category: 'drinks' },
  { name: 'Тан (200 мл)', calories: 48, protein: 1.8, carbs: 3, fat: 2.8, category: 'drinks' },

  // ═══════════════ АЛКОГОЛЬ ═══════════════
  { name: 'Пиво светлое (330 мл)', calories: 135, protein: 1, carbs: 11, fat: 0, category: 'drinks' },
  { name: 'Пиво тёмное (330 мл)', calories: 165, protein: 1, carbs: 14, fat: 0, category: 'drinks' },
  { name: 'Пиво безалкогольное (330 мл)', calories: 83, protein: 0.7, carbs: 18, fat: 0, category: 'drinks' },
  { name: 'Вино красное (150 мл)', calories: 125, protein: 0, carbs: 4, fat: 0, category: 'drinks' },
  { name: 'Вино белое (150 мл)', calories: 121, protein: 0, carbs: 4, fat: 0, category: 'drinks' },
  { name: 'Шампанское (150 мл)', calories: 89, protein: 0, carbs: 2, fat: 0, category: 'drinks' },
  { name: 'Водка (50 мл)', calories: 115, protein: 0, carbs: 0, fat: 0, category: 'drinks' },
  { name: 'Виски (50 мл)', calories: 110, protein: 0, carbs: 0, fat: 0, category: 'drinks' },

  // ═══════════════ СЛАДОСТИ И ДЕСЕРТЫ ═══════════════
  { name: 'Шоколад тёмный (30г)', calories: 170, protein: 2, carbs: 15, fat: 12, category: 'sweets' },
  { name: 'Шоколад молочный (30г)', calories: 160, protein: 2, carbs: 17, fat: 9, category: 'sweets' },
  { name: 'Шоколад белый (30г)', calories: 165, protein: 2, carbs: 18, fat: 10, category: 'sweets' },
  { name: 'Шоколадный батончик (50г)', calories: 245, protein: 3, carbs: 30, fat: 13, category: 'sweets' },
  { name: 'Конфета шоколадная (1 шт)', calories: 55, protein: 0.5, carbs: 6, fat: 3, category: 'sweets' },
  { name: 'Конфета карамельная (1 шт)', calories: 32, protein: 0, carbs: 8, fat: 0.2, category: 'sweets' },
  { name: 'Мёд (1 ст.л.)', calories: 64, protein: 0.1, carbs: 17, fat: 0, category: 'sweets' },
  { name: 'Варенье (1 ст.л.)', calories: 46, protein: 0, carbs: 12, fat: 0, category: 'sweets' },
  { name: 'Сгущёнка (1 ст.л.)', calories: 52, protein: 1, carbs: 9, fat: 1.4, category: 'sweets' },
  { name: 'Нутелла (1 ст.л.)', calories: 100, protein: 1, carbs: 11, fat: 6, category: 'sweets' },
  { name: 'Зефир (1 шт)', calories: 100, protein: 1, carbs: 25, fat: 0, category: 'sweets' },
  { name: 'Пастила (1 шт)', calories: 80, protein: 0.5, carbs: 20, fat: 0, category: 'sweets' },
  { name: 'Мармелад (1 шт)', calories: 32, protein: 0, carbs: 8, fat: 0, category: 'sweets' },
  { name: 'Халва (30г)', calories: 156, protein: 4, carbs: 14, fat: 10, category: 'sweets' },
  { name: 'Козинак (30г)', calories: 140, protein: 4, carbs: 13, fat: 8, category: 'sweets' },
  { name: 'Печенье овсяное (1 шт)', calories: 85, protein: 1, carbs: 12, fat: 4, category: 'sweets' },
  { name: 'Печенье песочное (1 шт)', calories: 75, protein: 1, carbs: 9, fat: 4, category: 'sweets' },
  { name: 'Печенье шоколадное (1 шт)', calories: 90, protein: 1, carbs: 11, fat: 5, category: 'sweets' },
  { name: 'Вафли (1 шт)', calories: 95, protein: 1, carbs: 10, fat: 6, category: 'sweets' },
  { name: 'Сушки (1 шт)', calories: 30, protein: 1, carbs: 6, fat: 0.3, category: 'sweets' },
  { name: 'Баранка (1 шт)', calories: 40, protein: 1, carbs: 8, fat: 0.5, category: 'sweets' },
  { name: 'Кекс (1 кусок)', calories: 310, protein: 4, carbs: 42, fat: 14, category: 'sweets' },
  { name: 'Маффин шоколадный (1 шт)', calories: 367, protein: 5, carbs: 46, fat: 18, category: 'sweets' },
  { name: 'Пончик (1 шт)', calories: 289, protein: 4, carbs: 33, fat: 16, category: 'sweets' },
  { name: 'Торт Наполеон (1 кусок)', calories: 350, protein: 5, carbs: 35, fat: 22, category: 'sweets' },
  { name: 'Торт Медовик (1 кусок)', calories: 310, protein: 4, carbs: 38, fat: 16, category: 'sweets' },
  { name: 'Торт шоколадный (1 кусок)', calories: 370, protein: 5, carbs: 40, fat: 22, category: 'sweets' },
  { name: 'Чизкейк (1 кусок)', calories: 320, protein: 6, carbs: 26, fat: 22, category: 'sweets' },
  { name: 'Тирамису', calories: 283, protein: 5, carbs: 25, fat: 18, category: 'sweets' },
  { name: 'Панна-котта', calories: 250, protein: 4, carbs: 21, fat: 17, category: 'sweets' },
  { name: 'Эклер (1 шт)', calories: 210, protein: 4, carbs: 20, fat: 13, category: 'sweets' },
  { name: 'Пирожное картошка (1 шт)', calories: 280, protein: 3, carbs: 30, fat: 17, category: 'sweets' },
  { name: 'Блинчики с Нутеллой (2 шт)', calories: 310, protein: 5, carbs: 38, fat: 16, category: 'sweets' },
  { name: 'Мороженое шоколадное (100г)', calories: 216, protein: 4, carbs: 28, fat: 10, category: 'sweets' },
  { name: 'Мороженое ванильное (100г)', calories: 201, protein: 3.5, carbs: 24, fat: 11, category: 'sweets' },
  { name: 'Мороженое фруктовый лёд (1 шт)', calories: 70, protein: 0, carbs: 18, fat: 0, category: 'sweets' },
  { name: 'Сахар (1 ч.л.)', calories: 20, protein: 0, carbs: 5, fat: 0, category: 'sweets' },
  { name: 'Сахарозаменитель (1 таб.)', calories: 0, protein: 0, carbs: 0, fat: 0, category: 'sweets' },

  // ═══════════════ СНЕКИ И ЗАКУСКИ ═══════════════
  { name: 'Чипсы (30г)', calories: 160, protein: 2, carbs: 15, fat: 10, category: 'snacks' },
  { name: 'Сухарики (30г)', calories: 130, protein: 3, carbs: 20, fat: 4, category: 'snacks' },
  { name: 'Попкорн (30г)', calories: 115, protein: 3, carbs: 18, fat: 4, category: 'snacks' },
  { name: 'Попкорн без масла (30г)', calories: 90, protein: 3, carbs: 19, fat: 1, category: 'snacks' },
  { name: 'Крекеры (30г)', calories: 140, protein: 3, carbs: 20, fat: 5, category: 'snacks' },
  { name: 'Сушёная рыба (30г)', calories: 90, protein: 17, carbs: 0, fat: 2, category: 'snacks' },
  { name: 'Энергетический батончик', calories: 210, protein: 8, carbs: 28, fat: 8, category: 'snacks' },
  { name: 'Протеиновый батончик', calories: 200, protein: 20, carbs: 22, fat: 7, category: 'snacks' },
  { name: 'Гематоген (1 шт)', calories: 130, protein: 2, carbs: 22, fat: 4, category: 'snacks' },
  { name: 'Рисовые чипсы (30г)', calories: 130, protein: 2, carbs: 22, fat: 4, category: 'snacks' },

  // ═══════════════ СПОРТИВНОЕ ПИТАНИЕ ═══════════════
  { name: 'Протеин сывороточный (30г)', calories: 117, protein: 24, carbs: 2, fat: 1.5, category: 'sports' },
  { name: 'Протеин казеиновый (30г)', calories: 112, protein: 24, carbs: 3, fat: 0.5, category: 'sports' },
  { name: 'Гейнер (порция)', calories: 370, protein: 20, carbs: 60, fat: 5, category: 'sports' },
  { name: 'BCAA (порция)', calories: 5, protein: 1, carbs: 0, fat: 0, category: 'sports' },
  { name: 'Креатин (5г)', calories: 0, protein: 0, carbs: 0, fat: 0, category: 'sports' },
  { name: 'Изотоник (500 мл)', calories: 105, protein: 0, carbs: 26, fat: 0, category: 'sports' },

  // ═══════════════ ДЕТСКОЕ / ЗАВТРАКИ ═══════════════
  { name: 'Каша быстрого приготовления (пакет)', calories: 110, protein: 3, carbs: 20, fat: 2, category: 'grains' },
  { name: 'Кукурузные хлопья (30г)', calories: 110, protein: 2, carbs: 25, fat: 0.3, category: 'grains' },
  { name: 'Шоколадные шарики (30г)', calories: 120, protein: 2, carbs: 24, fat: 2, category: 'grains' },
  { name: 'Тост с авокадо', calories: 195, protein: 3, carbs: 17, fat: 13, category: 'meals' },
  { name: 'Тост с арахисовой пастой', calories: 190, protein: 7, carbs: 18, fat: 10, category: 'meals' },
  { name: 'Каша на воде с мёдом', calories: 105, protein: 3, carbs: 20, fat: 1.7, category: 'meals' },
];

// Category labels for UI
export const FOOD_CATEGORIES: Record<string, string> = {
  dairy: '🥛 Молочные',
  meat: '🥩 Мясо и птица',
  fish: '🐟 Рыба и морепродукты',
  eggs: '🥚 Яйца',
  grains: '🌾 Крупы и гарниры',
  bread: '🍞 Хлеб и выпечка',
  vegetables: '🥬 Овощи',
  fruits: '🍎 Фрукты и ягоды',
  nuts: '🥜 Орехи и семена',
  oils: '🫒 Масла и соусы',
  meals: '🍲 Готовые блюда',
  fastfood: '🍟 Фастфуд',
  drinks: '☕ Напитки',
  sweets: '🍫 Сладости и десерты',
  snacks: '🍿 Снеки и закуски',
  sports: '💪 Спортивное питание',
};

export function searchFoods(query: string): FoodDBItem[] {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return FOOD_DATABASE.filter(f => f.name.toLowerCase().includes(q)).slice(0, 8);
}

export function getFoodsByCategory(category: string): FoodDBItem[] {
  return FOOD_DATABASE.filter(f => f.category === category);
}

export function getAllCategories(): string[] {
  return [...new Set(FOOD_DATABASE.map(f => f.category).filter(Boolean))] as string[];
}
